seperator = " "

[[module]]
prefix = " "
command = "uname -r"
update = false

[[module]]
prefix = "華 "
built_in = "load"
delay = 900

[[module]]
prefix = " "
built_in = "date"
delay = 43200000

[[module]]
prefix = " "
built_in = "time"

[[module]]
prefix = " "
built_in = "uptime"

[[module]]
prefix = " "
built_in = "cpu"

[[module]]
prefix = " "
built_in = "mem"
